# Generated by Django 4.0.4 on 2022-05-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('question3', models.CharField(max_length=100)),
                ('question4', models.CharField(max_length=100)),
                ('answer_number', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problemList_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='problemList_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problemlist'),
        ),
    ]
